#!/usr/bin/env bash
# Docker-Claude installer for macOS and Linux.
#
#   curl -fsSL https://raw.githubusercontent.com/Tanz0rz/Docker-Claude/main/install.sh | bash
#
# Fetches the repo to a fixed location and drops `cclaude` / `ccodex` launchers
# onto your PATH, so you can run either agent from any project directory without
# cloning by hand or editing shell aliases. Re-run any time to update.
set -euo pipefail

REPO_URL="${DOCKER_CLAUDE_REPO:-https://github.com/Tanz0rz/Docker-Claude.git}"
BRANCH="${DOCKER_CLAUDE_BRANCH:-main}"
INSTALL_DIR="${DOCKER_CLAUDE_HOME:-${XDG_DATA_HOME:-$HOME/.local/share}/docker-claude}"
BIN_DIR="${DOCKER_CLAUDE_BIN:-$HOME/.local/bin}"

# By default we never touch your shell config — we just print how to add the
# launchers to PATH. Opt in to have the installer edit your rc for you with the
# --modify-path flag or DOCKER_CLAUDE_MODIFY_PATH=1.
MODIFY_PATH="${DOCKER_CLAUDE_MODIFY_PATH:-0}"
for arg in "$@"; do
  case "$arg" in
    --modify-path) MODIFY_PATH=1 ;;
  esac
done

info() { printf '  %s\n' "$*"; }
err()  { printf 'Error: %s\n' "$*" >&2; exit 1; }

# Which run script the launchers should call, per OS.
case "$(uname -s)" in
  Darwin) RUN_REL="macos/run.sh" ;;
  Linux)  RUN_REL="linux/run.sh" ;;
  *) err "unsupported OS '$(uname -s)'. On Windows use install.ps1 instead." ;;
esac

echo "Installing Docker-Claude..."

# Fetch or update the repo into a fixed, managed location. The install dir is
# ours to overwrite — treat it as a checkout that always matches the remote.
if [ -d "$INSTALL_DIR/.git" ]; then
  info "Updating existing install in $INSTALL_DIR"
  git -C "$INSTALL_DIR" fetch --quiet origin "$BRANCH"
  git -C "$INSTALL_DIR" reset --hard --quiet "origin/$BRANCH"
elif command -v git >/dev/null 2>&1; then
  info "Cloning into $INSTALL_DIR"
  rm -rf "$INSTALL_DIR"
  mkdir -p "$(dirname "$INSTALL_DIR")"
  git clone --quiet --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
else
  # No git: fall back to a tarball download (GitHub URLs only).
  command -v curl >/dev/null 2>&1 || err "need either git or curl installed"
  info "git not found — downloading tarball into $INSTALL_DIR"
  rm -rf "$INSTALL_DIR"; mkdir -p "$INSTALL_DIR"
  curl -fsSL "${REPO_URL%.git}/archive/refs/heads/${BRANCH}.tar.gz" \
    | tar -xz --strip-components=1 -C "$INSTALL_DIR" \
    || err "failed to download the release tarball"
fi

RUN_SCRIPT="$INSTALL_DIR/$RUN_REL"
[ -f "$RUN_SCRIPT" ] || err "run script not found at $RUN_SCRIPT"
chmod +x "$RUN_SCRIPT"

# Write the launcher shims. They're tiny wrappers that exec the run script with
# the right AGENT; pointing at the fixed install dir means nothing breaks if the
# user's shell rc or working directory changes.
mkdir -p "$BIN_DIR"
make_shim() {
  local name="$1" agent="$2" path="$BIN_DIR/$1"
  {
    printf '#!/usr/bin/env bash\n'
    printf '# Generated by the Docker-Claude installer. Re-run install.sh to refresh.\n'
    [ -n "$agent" ] && printf 'export AGENT=%s\n' "$agent"
    printf 'exec "%s" "$@"\n' "$RUN_SCRIPT"
  } > "$path"
  chmod +x "$path"
}
make_shim cclaude ""
make_shim ccodex "codex"
info "Installed launchers -> $BIN_DIR/cclaude, $BIN_DIR/ccodex"

# Figure out whether the launchers are already callable, and which rc file new
# shells would source — used for the instructions below (and for the opt-in edit).
case ":$PATH:" in
  *":$BIN_DIR:"*) ON_PATH=1 ;;
  *)             ON_PATH=0 ;;
esac
case "$(basename "${SHELL:-}")" in
  zsh)  RC="$HOME/.zshrc" ;;
  bash) RC="$HOME/.bashrc" ;;
  *)    RC="$HOME/.profile" ;;
esac
PATH_LINE="export PATH=\"$BIN_DIR:\$PATH\""

# Only edit the rc when explicitly asked. Default is hands-off: explain instead.
DID_MODIFY=0
if [ "$ON_PATH" -eq 0 ] && [ "$MODIFY_PATH" -eq 1 ]; then
  MARKER="# added by docker-claude installer"
  if ! { [ -f "$RC" ] && grep -qF "$MARKER" "$RC"; }; then
    printf '\n%s  %s\n' "$PATH_LINE" "$MARKER" >> "$RC"
    info "Added $BIN_DIR to your PATH in $RC (--modify-path)"
  fi
  DID_MODIFY=1
fi

echo
echo "Done — cclaude launches Claude Code, ccodex launches the Codex CLI."
echo
if [ "$ON_PATH" -eq 1 ]; then
  echo "You're all set. From any project directory, run:"
  echo "    cclaude"
elif [ "$DID_MODIFY" -eq 1 ]; then
  echo "$BIN_DIR was added to your PATH in $RC."
  echo "Restart your shell (or run the line below), then run 'cclaude':"
  echo "    $PATH_LINE"
else
  echo "Last step — add the launchers to your PATH ($BIN_DIR isn't on it yet):"
  echo
  echo "  • For this shell only, run:"
  echo "        $PATH_LINE"
  echo
  echo "  • To make it permanent, add that line to $RC and restart your shell."
  echo
  echo "  (Prefer the installer to do this? Re-run with --modify-path.)"
  echo
  echo "Then, from any project directory, run:  cclaude"
fi
echo
echo "The first launch builds the image and prompts you to /login."
